# Site settings
title: AJ Book
url: 'https://secondbook5.github.io/'
description: Research Assistant at Memorial Sloan Kettering studying persistent immune and tissue states through quantitative imaging, regulatory genomics, and interpretable computational modeling.
author: Abraham J. Book
lang: en-US

theme_skin: olive
chrome_mobile_color:

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes
plugins:
  - jekyll-sitemap

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development settings
port: 4000
host: 0.0.0.0
safe: false
