# Site Settings
title: AJ Book
url: 'https://secondbook5.github.io/'
description: Research Assistant at Memorial Sloan Kettering studying biological memory, immune and tissue-state dynamics through quantitative imaging, radiobiology, single-cell and spatial transcriptomics, and interpretable computational modeling.

theme_skin: olive
chrome_mobile_color:

# Tracker
analytics: G-V23DQT85GG

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

sass:
  sass_dir: _sass
  style: compressed

# Site Settings
sidebar:
  position: right

plugins:
  - jekyll-seo-tag
